# Generated by Django 5.2.10 on 2026-02-13 20:21

import django.core.validators
from django.db import migrations, models

import hr_access.managers
import hr_common.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("email", hr_common.db.fields.NormalizedEmailField(max_length=254, unique=True, verbose_name="email address")),
                ("role", models.CharField(choices=[("global_admin", "Global Admin"), ("site_admin", "Site Admin"), ("user", "User")], default="user", max_length=20)),
                ("first_name", models.CharField(blank=True, max_length=254, verbose_name="First Name")),
                ("last_name", models.CharField(blank=True, max_length=254, verbose_name="Last Name")),
                ("username", models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(5)])),
                ("username_ci", models.CharField(db_index=True, editable=False, max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("password_changed_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "users",
                "ordering": ["email"],
            },
            managers=[
                ("objects", hr_access.managers.UserManager()),
            ],
        ),
    ]
