# Generated by Django 5.0.6 on 2024-06-23 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_access', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
