"""
Django settings for hellaWebtilian project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from dotenv import load_dotenv
from pathlib import Path

from django.core.management.utils import get_random_secret_key

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR/'.env')


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return str(value).strip().lower() in ('1', 'true', 'yes', 'on')


SECRET_FILE = BASE_DIR / ".django_secret"

if SECRET_FILE.exists():
    SECRET_KEY = SECRET_FILE.read_text().strip()
else:
    SECRET_KEY = get_random_secret_key()
    SECRET_FILE.write_text(SECRET_KEY)
    SECRET_FILE.chmod(0o600)

# SECRET_KEY = 'django-insecure-+l)g&&h6i^d1-hz^&6%3+kc@bgq0h!@272q5#svy1++)h%b8&f'

DEBUG = _env_bool('DEBUG', False)

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.split()]

INTERNAL_IPS = ['127.0.0.1', ]

AUTHENTICATION_BACKENDS = [
    'hr_access.auth_backend.CustomBackend',
]

INSTALLED_APPS = [
    # ------------------------------------ #
    #       This block must be first       #
    # ------------------------------------ #
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',

    'hr_core',
    'hr_about',
    'hr_access',
    'hr_bulletin',
    'hr_common',
    'hr_email',
    'hr_live',
    'hr_payment',
    'hr_shop',
    'hr_site',
    'hr_storage',

    'debug_toolbar',
    'phonenumber_field',
    'django_browser_reload',
    'imagekit',
    'django_vite',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    MIDDLEWARE += ['django_browser_reload.middleware.BrowserReloadMiddleware']
    MIDDLEWARE.insert(2, 'debug_toolbar.middleware.DebugToolbarMiddleware',)


ROOT_URLCONF = 'hr_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

TEMPLATES[0]["OPTIONS"]["context_processors"] += [
    "hr_shop.context_processors.cart_context",
]

WSGI_APPLICATION = 'hr_django.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_USER_MODEL = 'hr_access.User'

AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY', '')

SITE_URL = os.getenv('SITE_URL', 'http://localhost:8000')
#
# from hr_email.provider_settings import get_email_config  # noqa: E402
# _email_config = get_email_config(prefer_provider_specific=True)

EMAIL_PROVIDER = os.environ.get("EMAIL_PROVIDER", "mailjet").strip().lower()

DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    "Hella Reptilian <mail@hellareptilian.com>",
)

EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend",
)

EMAIL_HOST = os.environ.get("EMAIL_HOST", "in-v3.mailjet.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_USE_TLS = _env_bool("EMAIL_USE_TLS", True)
EMAIL_USE_SSL = _env_bool("EMAIL_USE_SSL", False)

EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
MAILJET_API_KEY = os.environ.get("MAILJET_API_KEY") or EMAIL_HOST_USER
MAILJET_API_SECRET = os.environ.get("MAILJET_API_SECRET") or EMAIL_HOST_PASSWORD

if not DEBUG:
    if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
        raise RuntimeError("Email credentials must be set when DEBUG=False.")

#
# EMAIL_HOST = 'in-v3.mailjet.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')  # Mailjet API Key
# EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')  # Mailjet secret
# DEFAULT_FROM_EMAIL = 'Hella Reptilian <no-reply@hellareptilian.com>'

DJANGO_VITE = {
    "default": {
        "dev_mode": DEBUG,
        "dev_server_host": os.environ.get('VITE_DEV_SERVER_HOST'),
        "dev_server_port": os.environ.get('VITE_DEV_SERVER_PORT'),
        "static_url_prefix": "/",
    }
}
