# Generated by Django 5.0.6 on 2024-06-29 05:00

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=255, unique=True, verbose_name='Address')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('subdivision', models.CharField(max_length=255, verbose_name='State/Province')),
                ('postal_code', models.CharField(max_length=25, null=True, verbose_name='Zip')),
                ('country', models.CharField(max_length=255, null=True, verbose_name='Country')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=10, null=True, verbose_name='Day of the Week')),
            ],
        ),
        migrations.CreateModel(
            name='Booker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, max_length=255, null=True, verbose_name='Note')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='Nickname')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator])),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hr_live.address', verbose_name='Address')),
            ],
            options={
                'verbose_name_plural': 'bookers',
                'ordering': ['first_name', 'last_name', 'phone_number', 'email', 'nickname'],
            },
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Last Name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, null=True, validators=[django.core.validators.EmailValidator], verbose_name='Email')),
                ('note', models.TextField(blank=True, max_length=255, null=True, verbose_name='Note')),
                ('stage_name', models.CharField(max_length=50, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hr_live.address', verbose_name='Address')),
            ],
            options={
                'verbose_name_plural': 'musicians',
            },
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('website', models.URLField(max_length=255, null=True, unique=True, validators=[django.core.validators.URLValidator])),
                ('note', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Note')),
                ('contacts', models.ManyToManyField(related_name='contacts', to='hr_live.musician', verbose_name='Contacts')),
                ('members', models.ManyToManyField(related_name='projects', to='hr_live.musician', verbose_name='Members')),
            ],
            options={
                'verbose_name_plural': 'acts',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('website', models.URLField(max_length=250, null=True, unique=True, validators=[django.core.validators.URLValidator])),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='Email')),
                ('note', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Note')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venue', to='hr_live.address', verbose_name='Address')),
                ('bookers', models.ManyToManyField(related_name='venues', to='hr_live.booker')),
            ],
            options={
                'verbose_name_plural': 'venues',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None, null=True, verbose_name='Date')),
                ('time', models.TimeField(default=None, null=True, verbose_name='Time')),
                ('booker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='hr_live.booker', verbose_name='Booker')),
                ('lineup', models.ManyToManyField(related_name='shows', to='hr_live.act', verbose_name='Lineup')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='hr_live.venue', verbose_name='Venue')),
            ],
            options={
                'verbose_name_plural': 'shows',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='VenueBookerDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_live.booker')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hr_live.day')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_live.venue')),
            ],
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['name'], name='hr_live_ven_name_7ea237_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='venuebookerday',
            unique_together={('venue', 'day')},
        ),
    ]
