# Generated by Django 5.2.10 on 2026-02-10 18:06

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models

import hr_live.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr_common", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booker",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=50, verbose_name="First Name")),
                ("last_name", models.CharField(max_length=50, null=True, verbose_name="Last Name")),
                ("note", models.TextField(blank=True, max_length=255, null=True, verbose_name="Note")),
                ("email", models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name="Email")),
                ("phone_number", phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name="Phone")),
            ],
            options={
                "verbose_name_plural": "bookers",
                "ordering": ["first_name", "last_name", "phone_number", "email"],
            },
        ),
        migrations.CreateModel(
            name="Day",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        choices=[("MON", "Monday"), ("TUE", "Tuesday"), ("WED", "Wednesday"), ("THU", "Thursday"), ("FRI", "Friday"), ("SAT", "Saturday"), ("SUN", "Sunday")],
                        max_length=10,
                        null=True,
                        verbose_name="Day of the Week",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Musician",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=50, verbose_name="First Name")),
                ("last_name", models.CharField(max_length=50, null=True, verbose_name="Last Name")),
                ("note", models.TextField(blank=True, max_length=255, null=True, verbose_name="Note")),
                ("email", models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name="Email")),
                ("phone_number", phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name="Phone")),
            ],
            options={
                "verbose_name_plural": "musicians",
            },
        ),
        migrations.CreateModel(
            name="Act",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("website", models.URLField(max_length=255, null=True, unique=True, validators=[django.core.validators.URLValidator()])),
                ("note", models.TextField(blank=True, max_length=5000, null=True, verbose_name="Note")),
                ("contacts", models.ManyToManyField(related_name="contacts", to="hr_live.musician", verbose_name="Contacts")),
                ("members", models.ManyToManyField(related_name="projects", to="hr_live.musician", verbose_name="Members")),
            ],
            options={
                "verbose_name_plural": "acts",
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("note", models.TextField(blank=True, max_length=5000, null=True, verbose_name="Note")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Name")),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("website", models.URLField(max_length=250, null=True, unique=True, validators=[django.core.validators.URLValidator()])),
                ("email", models.EmailField(blank=True, max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name="Email")),
                ("phone_number", phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name="Phone")),
                ("address", models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name="venue", to="hr_common.address", verbose_name="Address")),
                ("bookers", models.ManyToManyField(related_name="venues", to="hr_live.booker", verbose_name="Bookers")),
            ],
            options={
                "verbose_name_plural": "venues",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(default=None, null=True, verbose_name="Date")),
                ("time", models.TimeField(default=None, null=True, verbose_name="Time")),
                ("image", models.ImageField(null=True, upload_to=hr_live.models.show_image_storage)),
                ("slug", models.SlugField(blank=True, help_text="URL identifier auto-generated from date and venue.", max_length=140, unique=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("published", "Published")], default="draft", max_length=10)),
                ("timezone", models.CharField(default="America/Chicago", max_length=50, verbose_name="Timezone")),
                ("booker", models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name="shows", to="hr_live.booker", verbose_name="Booker")),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="created", to=settings.AUTH_USER_MODEL)),
                ("lineup", models.ManyToManyField(related_name="shows", to="hr_live.act", verbose_name="Lineup")),
                ("modified_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="updated", to=settings.AUTH_USER_MODEL)),
                ("venue", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="shows", to="hr_live.venue", verbose_name="Venue")),
            ],
            options={
                "verbose_name_plural": "shows",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="VenueBookerDay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("booker", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="hr_live.booker")),
                ("day", models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="hr_live.day")),
                ("venue", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="hr_live.venue")),
            ],
        ),
        migrations.AddIndex(
            model_name="venue",
            index=models.Index(fields=["name"], name="hr_live_ven_name_7ea237_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="venuebookerday",
            unique_together={("venue", "day")},
        ),
    ]
