# Generated by Django 5.2.10 on 2026-03-07 10:30

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_common", "0001_initial"),
        ("hr_live", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venuebookerday",
            name="day",
            field=models.CharField(
                choices=[("MON", "Monday"), ("TUE", "Tuesday"), ("WED", "Wednesday"), ("THU", "Thursday"), ("FRI", "Friday"), ("SAT", "Saturday"), ("SUN", "Sunday")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="venuebookerday",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="act",
            name="note",
            field=models.TextField(blank=True, default="", max_length=5000, verbose_name="Note"),
        ),
        migrations.AlterField(
            model_name="act",
            name="website",
            field=models.URLField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booker",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254, verbose_name="Email"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booker",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=50, verbose_name="Last Name"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booker",
            name="note",
            field=models.TextField(blank=True, default="", max_length=255, verbose_name="Note"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booker",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default="", max_length=128, region=None, verbose_name="Phone"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="musician",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254, verbose_name="Email"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="musician",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=50, verbose_name="Last Name"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="musician",
            name="note",
            field=models.TextField(blank=True, default="", max_length=255, verbose_name="Note"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="musician",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default="", max_length=128, region=None, verbose_name="Phone"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="show",
            name="date",
            field=models.DateField(blank=True, default=None, null=True, verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="show",
            name="time",
            field=models.TimeField(blank=True, default=None, null=True, verbose_name="Time"),
        ),
        migrations.AlterField(
            model_name="venue",
            name="address",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name="venues", to="hr_common.address", verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="venue",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254, verbose_name="Email"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="venue",
            name="note",
            field=models.TextField(blank=True, default="", max_length=5000, verbose_name="Note"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="venue",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default="", max_length=128, region=None, verbose_name="Phone"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="venue",
            name="website",
            field=models.URLField(blank=True, default="", max_length=250),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="act",
            constraint=models.UniqueConstraint(condition=models.Q(("website", ""), _negated=True), fields=("website",), name="uniq_nonblank_act_website"),
        ),
        migrations.AddConstraint(
            model_name="venue",
            constraint=models.UniqueConstraint(condition=models.Q(("website", ""), _negated=True), fields=("website",), name="uniq_nonblank_venue_website"),
        ),
        migrations.AddConstraint(
            model_name="venue",
            constraint=models.UniqueConstraint(condition=models.Q(("email", ""), _negated=True), fields=("email",), name="uniq_nonblank_venue_email"),
        ),
        migrations.AddConstraint(
            model_name="venue",
            constraint=models.UniqueConstraint(condition=models.Q(("phone_number", ""), _negated=True), fields=("phone_number",), name="uniq_nonblank_venue_phone_number"),
        ),
        migrations.AddConstraint(
            model_name="venuebookerday",
            constraint=models.UniqueConstraint(fields=("venue", "day"), name="uniq_venue_booker_day"),
        ),
        migrations.DeleteModel(
            name="Day",
        ),
    ]
