# Generated by Django 5.0.6 on 2024-06-29 18:56

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_live', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='contacts',
            field=models.ManyToManyField(null=True, related_name='contacts', to='hr_live.musician', verbose_name='Contacts'),
        ),
        migrations.AlterField(
            model_name='act',
            name='members',
            field=models.ManyToManyField(null=True, related_name='projects', to='hr_live.musician', verbose_name='Members'),
        ),
        migrations.AlterField(
            model_name='booker',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='booker',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='booker',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='booker',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='show',
            name='booker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='hr_live.booker', verbose_name='Booker'),
        ),
        migrations.AlterField(
            model_name='show',
            name='lineup',
            field=models.ManyToManyField(null=True, related_name='shows', to='hr_live.act', verbose_name='Lineup'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='venue', to='hr_live.address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='bookers',
            field=models.ManyToManyField(null=True, related_name='venues', to='hr_live.booker', verbose_name='Bookers'),
        ),
    ]
