# Generated by Django 5.2.8 on 2026-01-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_live', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
    ]
