# Generated by Django 5.0.6 on 2024-06-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_live', '0002_alter_act_contacts_alter_act_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booker',
            name='address',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='address',
        ),
        migrations.AlterField(
            model_name='act',
            name='contacts',
            field=models.ManyToManyField(related_name='contacts', to='hr_live.musician', verbose_name='Contacts'),
        ),
        migrations.AlterField(
            model_name='act',
            name='members',
            field=models.ManyToManyField(related_name='projects', to='hr_live.musician', verbose_name='Members'),
        ),
        migrations.AlterField(
            model_name='show',
            name='lineup',
            field=models.ManyToManyField(related_name='shows', to='hr_live.act', verbose_name='Lineup'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='bookers',
            field=models.ManyToManyField(related_name='venues', to='hr_live.booker', verbose_name='Bookers'),
        ),
    ]
