# Generated by Django 5.0.6 on 2024-06-30 18:17

import hr_live.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_live', '0004_alter_musician_email_alter_musician_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='image',
            field=models.ImageField(null=True, upload_to=hr_live.models.show_image_storage),
        ),
    ]
