# hr_core/management/commands/build_responsive_backgrounds.py
from __future__ import annotations

from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand

from hr_core.config.backgrounds_config import SECTION_BACKGROUNDS, SECTION_WIPES

WIPE_WIDTHS = (960, 1440, 1920, 2560)
BACKGROUND_WIDTHS = (960, 1920)

# write into Vite source tree
OUT_ABS_PATH = Path(settings.BASE_DIR) / "hr_core" / "static_src" / "css" / "generated" / "responsive_backgrounds.css"


def _stem(name: str) -> str:
    return Path(name).stem


def _imageset_lines(bucket: str, subdir: str, stem: str, widths: tuple[int, ...]) -> list[str]:
    if widths == WIPE_WIDTHS:
        densities = ["1x", "1.5x", "2x", "3x"]
    else:
        densities = ["1x", "2x"]

    lines: list[str] = []
    for w, d in zip(widths, densities, strict=False):
        # This is a *URL path* at runtime, but in CSS it’s fine.
        # Nginx/Django will serve /static/hr_core/images/... in prod.
        url = f'/static/hr_core/images/{bucket}/{subdir}/{stem}-{w}w.webp'
        lines.append(f'      url("{url}") type("image/webp") {d},')
    if lines:
        lines[-1] = lines[-1].rstrip(",")  # remove trailing comma on last entry
    return lines


class Command(BaseCommand):
    help = "Generate responsive CSS (image-set) for parallax backgrounds and section wipes."

    def handle(self, *args, **options):
        OUT_ABS_PATH.parent.mkdir(parents=True, exist_ok=True)

        css: list[str] = []
        css.append("/* AUTO-GENERATED FILE. DO NOT EDIT. */")
        css.append("/* Generated by: python manage.py build_responsive_backgrounds */")
        css.append("")

        # WIPES
        for key, filename in SECTION_WIPES.items():
            stem = _stem(filename)
            fallback = f'/static/hr_core/images/wipes/{filename}'

            css.append(f"#section-wipe-{key}.section-wipe {{")
            css.append(f'  background-image: url("{fallback}");')
            css.append("}")
            css.append("")
            css.append("/* noinspection CssInvalidFunction,CssUnknownTarget */")
            css.append('@supports (background-image: image-set(url("x.webp") type("image/webp") 1x)) {')
            css.append(f"  #section-wipe-{key}.section-wipe {{")
            css.append("    background-image: image-set(")
            css.extend(_imageset_lines("wipes", "opt_webp", stem, WIPE_WIDTHS))
            css.append("    );")
            css.append("  }")
            css.append("}")
            css.append("")

        # BACKGROUNDS
        for key, filename in SECTION_BACKGROUNDS.items():
            stem = _stem(filename)
            fallback = f'/static/hr_core/images/backgrounds/{filename}'

            css.append(f"#parallax-section-{key} .parallax-background {{")
            css.append(f'  background-image: url("{fallback}");')
            css.append("}")
            css.append("")
            css.append("/* noinspection CssInvalidFunction,CssUnknownTarget */")
            css.append('@supports (background-image: image-set(url("x.webp") type("image/webp") 1x)) {')
            css.append(f"  #parallax-section-{key} .parallax-background {{")
            css.append("    background-image: image-set(")
            css.extend(_imageset_lines("backgrounds", "bg_opt", stem, BACKGROUND_WIDTHS))
            css.append("    );")
            css.append("  }")
            css.append("}")
            css.append("")

        OUT_ABS_PATH.write_text("\n".join(css) + "\n", encoding="utf-8")
        self.stdout.write(self.style.SUCCESS(f"Wrote {OUT_ABS_PATH}"))
