# _seed_data/hr_shop/Divine Hoodie/product.yml
# Product Seed Configuration
# ======================================================

Product: "Divine Hoodie"

description: "Holy hoodies. Specifically, four holes."
default_price: 40.00
active: true

option_types:
  Size: ["S", "M", "L", "XL"]
  Color: ["Cloud", "Open Sky", "Creation"]
