# Generated by ChatGPT on 2025-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PendingVariant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("recipe_key", models.CharField(db_index=True, max_length=32)),
                ("src_name", models.TextField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
            ],
            options={},
        ),
        migrations.AddConstraint(
            model_name="pendingvariant",
            constraint=models.UniqueConstraint(fields=("recipe_key", "src_name"), name="uq_pending_variant_recipe_src"),
        ),
    ]
