# _seed_data/hr_shop/Sticker Set/product.yml
# Product Seed Configuration
# ======================================================

Product: "Sticker Set"
image_key: "variants/sticker_set-green.png"

description: "A set of stickers for sticking."
default_price: 20.00
active: true

option_types:
  Color: ["Green"]
