# Generated by Django 5.2.10 on 2026-02-04 09:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr_shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("type", models.CharField(db_index=True, max_length=255)),
                ("payload", models.JSONField()),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("ok", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider_session_id", models.CharField(blank=True, max_length=255, null=True)),
                ("client_secret", models.CharField(blank=True, max_length=255, null=True)),
                ("provider_payment_intent_id", models.CharField(blank=True, max_length=255, null=True)),
                ("failure_code", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                            ("canceled", "Canceled"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(default="stripe", max_length=32)),
                ("currency", models.CharField(default="usd", max_length=10)),
                ("amount_cents", models.PositiveIntegerField(default=0)),
                ("failure_message", models.TextField(blank=True, null=True)),
                ("raw", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payment_attempts", to="hr_shop.order")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["order", "created_at"], name="hr_payment__order_i_46fd2c_idx"),
                    models.Index(fields=["provider_session_id"], name="hr_payment__provide_02e729_idx"),
                    models.Index(fields=["provider_payment_intent_id"], name="hr_payment__provide_9508e2_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("provider_session_id__isnull", False)), fields=("provider_session_id",), name="uq_paymentattempt_provider_session_id_not_null"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("provider_payment_intent_id__isnull", False)),
                        fields=("provider_payment_intent_id",),
                        name="uq_paymentattempt_payment_intent_id_not_null",
                    ),
                ],
            },
        ),
    ]
