# _seed_data/hr_shop/Super Offiscale T-Shirt/product.yml
# Product Seed Configuration
# ======================================================

Product: "Super Offiscale T-Shirt"

description: "An Approved T-Shirt."
default_price: 30.00
active: true

option_types:
  Size: ["S", "M", "L", "XL"]
  Color: ["Aqua", "Black", "Blue", "Pink"]
