# Generated by Django 5.2.10 on 2026-02-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fingerprint", models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ("street_address", models.CharField(max_length=255, verbose_name="Address")),
                ("street_address_line2", models.CharField(blank=True, max_length=255, null=True, verbose_name="Address Line 2")),
                (
                    "building_type",
                    models.CharField(
                        choices=[("single_family", "Single family home"), ("apartment", "Apartment / Condo"), ("business", "Business"), ("po_box", "P.O. Box"), ("other", "Other")],
                        default="single_family",
                        max_length=20,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=50, null=True, verbose_name="Apt/Office/Unit")),
                ("city", models.CharField(max_length=255, verbose_name="City")),
                ("subdivision", models.CharField(max_length=100, verbose_name="State/Province")),
                ("postal_code", models.CharField(max_length=25, verbose_name="Zip")),
                ("country", models.CharField(max_length=255, verbose_name="Country")),
            ],
            options={
                "verbose_name_plural": "Addresses",
            },
        ),
    ]
