# Generated by Django 5.2.10 on 2026-02-28 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_shop", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="products", to="hr_shop.productimage"),
        ),
        migrations.AlterField(
            model_name="checkoutdraft",
            name="note",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="customer",
            name="middle_initial",
            field=models.CharField(blank=True, default="", max_length=5),
        ),
        migrations.AlterField(
            model_name="customer",
            name="suffix",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="orders", to="hr_shop.customer"),
        ),
        migrations.AlterField(
            model_name="order",
            name="note",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="order",
            name="stripe_checkout_session_id",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="orders", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="is_display_variant",
            field=models.BooleanField(default=False, help_text="If set, this variant will be used as the product default display variant."),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="slug",
            field=models.SlugField(blank=True, max_length=160),
        ),
    ]
