# Generated by Django 5.2.10 on 2026-03-07 10:30

from decimal import Decimal

import django.core.validators
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_shop", "0002_product_image_alter_checkoutdraft_note_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="image",
            new_name="default_image",
        ),
        migrations.AlterUniqueTogether(
            name="optiontypetemplate",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="optionvaluetemplate",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="productoptiontype",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="productoptionvalue",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="productvariantoption",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default="", max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="optiontypetemplate",
            name="code",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal("0"))]),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(condition=models.Q(("phone", ""), _negated=True), fields=("phone",), name="uniq_nonblank_customer_phone"),
        ),
        migrations.AddConstraint(
            model_name="optionvaluetemplate",
            constraint=models.UniqueConstraint(fields=("option_type", "code"), name="uniq_together_opt_val_temp__option_type_code"),
        ),
        migrations.AddConstraint(
            model_name="productoptiontype",
            constraint=models.UniqueConstraint(fields=("product", "code"), name="uniq_together_product_option_type__product_code"),
        ),
        migrations.AddConstraint(
            model_name="productoptiontype",
            constraint=models.UniqueConstraint(fields=("product", "name"), name="uniq_together_product_option_type__product_name"),
        ),
        migrations.AddConstraint(
            model_name="productoptionvalue",
            constraint=models.UniqueConstraint(fields=("option_type", "code"), name="uniq_together_product_option_value__option_type_code"),
        ),
        migrations.AddConstraint(
            model_name="productvariantoption",
            constraint=models.UniqueConstraint(fields=("variant", "option_value"), name="uniq_together_prod_var_opt__variant_option_value"),
        ),
    ]
